branches:
  except:
    - gh-pages
language: perl
perl:
  - "5.16"
before_install:
  - sudo apt-get install libtext-aspell-perl aspell-es
  - cd Text-HashSlash
script: "perl Makefile.PL && make test"
